// دیتابیس کامل ۱۵۸ روستای الموت
const alamutVillages = [
  // الموت شرقی
  { id: 1, name: "معلم کلایه", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "مرکز بخش الموت شرقی." },
  { id: 2, name: "گازرخان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستای پای قلعه حسن صباح." },
  { id: 3, name: "گرمارود سینا", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 4, name: "گرمارود پیر", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 5, name: "آتان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "ماسوله الموت با بافت پلکانی." },
  { id: 6, name: "کلایه", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 7, name: "هنیز", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "مبداء صعود به قله سیالان." },
  { id: 8, name: "چلاسر", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 9, name: "شترخان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 10, name: "اویرک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 11, name: "ورک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 12, name: "انوه", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 13, name: "اندج", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "دره و صخره‌های زیبای اندج." },
  { id: 14, name: "کوچین", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 15, name: "دیکین", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در نزدیکی دریاچه اوان." },
  { id: 16, name: "زرآباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستای درخت خونبار زرآباد." },
  { id: 17, name: "اوان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستای دریاچه زیبای اوان." },
  { id: 18, name: "زوارک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 19, name: "حسن‌آباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 20, name: "محمودآباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 21, name: "شهرک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 22, name: "شمس کلایه", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 23, name: "علی‌آباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 24, name: "میانه", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 25, name: "خشکچال", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 26, name: "آفتابدر", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 27, name: "طاله", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 28, name: "رجایی دشت", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "از مراکز مهم و پرجمعیت الموت." },
  { id: 29, name: "اسپیدول", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 30, name: "تیرگ", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 31, name: "جوستان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 32, name: "سفیددره", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 33, name: "سوهان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 34, name: "سیاهدشت", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 35, name: "عسل محله", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 36, name: "مدان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 37, name: "هرانک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 38, name: "باغدشت", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 39, name: "بالاروچ", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 40, name: "پایین‌روچ", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 41, name: "پیچ بن", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "گردنه و کاروانسرای تاریخی پیچ‌بن." },
  { id: 42, name: "تنوره", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 43, name: "توجان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 44, name: "جولاده", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 45, name: "چریشک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 46, name: "حسین‌آباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 47, name: "خسروبان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 48, name: "دهک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 49, name: "دربند", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 50, name: "دشتک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 51, name: "دیلمدشت", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 52, name: "زردچال", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 53, name: "سردشت", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 54, name: "سلطان دشت", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 55, name: "سلمبار", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در گردنه سلمبار." },
  { id: 56, name: "سیردان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 57, name: "شترک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 58, name: "شورستان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 59, name: "طاهرآباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 60, name: "عناپ", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 61, name: "فلار", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 62, name: "قسطین", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 63, name: "کلمین", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 64, name: "کوشک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 65, name: "گورار", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 66, name: "میراخور", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 67, name: "مینودشت", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 68, name: "ناوه", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 69, name: "نسا", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 70, name: "وارک", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 71, name: "وانقین", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 72, name: "ویرجان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 73, name: "هریف", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 74, name: "یوج", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 75, name: "آتان کلا", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 76, name: "اوات", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 77, name: "ایلاق", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 78, name: "باغ کلایه", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 79, name: "تلاتر", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 80, name: "جلوان", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 81, name: "سرخه ده", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 82, name: "سفیدآب", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 83, name: "شمس‌آباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 84, name: "عباس‌آباد", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 85, name: "قسطین رود", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 86, name: "کارندچال", section: "الموت شرقی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },

  // الموت غربی
  { id: 87, name: "رازمیان", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "مرکز بخش الموت غربی و باغات فندق و خرمالو." },
  { id: 88, name: "بهرام آباد", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 89, name: "هیر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "پایتخت زغال‌اخته ایران با باغات سرسبز." },
  { id: 90, name: "ویار", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی با چشمه‌ها و طبیعت کوهستانی زیبا." },
  { id: 91, name: "سپارده", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "مرز بین قزوین و مازندران." },
  { id: 92, name: "فلار غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 93, name: "یوج غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 94, name: "آکوجان", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی با غار طبیعی و باغات فندق." },
  { id: 95, name: "دستجرد", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 96, name: "لات", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 97, name: "علندر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 98, name: "کنگرین", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 99, name: "رجین", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 100, name: "فشک", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 101, name: "قسطین لار", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 102, name: "سیاهکوه", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 103, name: "تلاتر غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 104, name: "کاظم‌آباد", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 105, name: "خوشکاب", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 106, name: "قسطین ناحیه", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 107, name: "ارکن ترک", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 108, name: "ارکن کرد", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 109, name: "اسپیددر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 110, name: "ازگنین بالا", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 111, name: "ازگنین پایین", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 112, name: "اشترک", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 113, name: "امامزاده هارون", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 114, name: "امیرآباد", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 115, name: "اواتر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 116, name: "بادمجین", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 117, name: "برسر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 118, name: "بلکان", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 119, name: "بنگین", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 120, name: "پروش", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 121, name: "پشتروک", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 122, name: "تله سر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 123, name: "تنوره غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 124, name: "چاله", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 125, name: "حسن‌آباد غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 126, name: "حسین‌آباد غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 127, name: "خسروبان غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 128, name: "خلندر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 129, name: "دارسر", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 130, name: "درچاک", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 131, name: "دربی کلا", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 132, name: "دستجرد علیا", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 133, name: "دستجرد سفلی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 134, name: "دوران", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 135, name: "دهک غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 136, name: "دیدار", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 137, name: "رباط", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 138, name: "زرآباد غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 139, name: "سردشت غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 140, name: "سرخه ده غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 141, name: "سفیددره غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 142, name: "سلطان‌آباد", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 143, name: "سیاهدشت غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 144, name: "شترک غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 145, name: "شمس‌آباد غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 146, name: "شورستان غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 147, name: "طاهرآباد غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 148, name: "عباس‌آباد غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت شرقی." },
  { id: 149, name: "علی‌آباد غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 150, name: "قاسم‌آباد", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 151, name: "کاکوهستان", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 152, name: "کشرود", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 153, name: "کلات", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 154, name: "کنگرین سفلی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 155, name: "گورار غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 156, name: "مارکین", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 157, name: "میراخور غربی", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." },
  { id: 158, name: "نیارک", section: "الموت غربی", status: "در دست تکمیل", photos: { cover: "images/villages/placeholder.jpg", gallery: [] }, desc: "روستایی در الموت غربی." }
];
